apiVersion: v1
kind: Service
metadata:
  name: wedding-pictures-service
  namespace: wedding
  labels:
    app: wedding-pictures
spec:
  type: ClusterIP
  selector:
    app: wedding-pictures
  ports:
    - port: 8080
      targetPort: 8080
